#!/bin/bash

### BEGIN INIT INFO
# Provides:          monitor-service
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:		
# Short-Description: Service which monitors the VPN server and the system
### END INIT INFO

exe="/usr/sbin/monitor.py"


start() {
	echo "Starting monitor service"
	instance=$(pgrep -fl monitor.py)
	if [ -n "$instance" ]
	then
		echo "Already running."
	else
		python3 $exe > /dev/null 2>&1 &
	fi
}

stop() {
    echo "Shutting down monitor service"
    kill -9 $(pgrep -f monitor.py)
}

restart() {
    echo "Restarting monitor service"
    stop
    sleep 2
    start
}

status(){
	echo stat -c %y exe
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
    ;; esac

exit 0
